ds:
  retry:
    max: "10"
    interval: "20"
  timer:
    cron: ""
  fhir:
    store:
      url: "http://bridgehead-bbmri-blaze:8080/fhir"
  directory:
    url: "https://directory-backend.molgenis.net"
    user:
      name: ""
      pass: ""
    default_collection_id:
    allow_star_model: "False"
    min_donors: "10"
    max_facts: "-1"
    mock: "False"
    only_login: "False"
logging:
  level:
    root: error
