ds:
  retry:
    max: "3"
    interval: "200"
  timer:
    cron: ""
  fhir:
    store:
      url: "http://bridgehead-bbmri-blaze:8080/fhir"
  directory:
    url: "https://directory-backend.molgenis.net"
    user:
      name: ""
      pass: ""
    default_collection_id:
    allow_star_model: "False"
    min_donors: "10"
    max_facts: "-1"
    mock: "False"
    only_login: "False"
    write_to_file: "False"
    output_directory: "/tmp"
  import:
    biobanks: "False"
    collections: "False"
# HAPI FHIR floods the logs at the INFO level, so cut off at WARN
logging:
  level:
    ca:
      uhn:
        fhir: "WARN"

