ds:
  retry:
    max: "10"
    interval: "20"
  timer:
    cron: ""
  fhir:
    store:
      url: "http://bridgehead-bbmri-blaze:8080"
  directory:
    url: "https://directory.bbmri-eric.eu"
    user:
      name: ""
      pass: ""
    default_collection_id:
    allow_star_model: "False"
    min_donors: "10"


