name: Build with maven and docker

on:
  push:
    branches:
    - master
    - develop
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+**'
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 19

    - name: Cache Local Maven Repo
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: maven-${{ hashFiles('pom.xml') }}

    - name: Build with Maven
      run: mvn -B install

    # BEGIN: integration testing

    - name: Build local Directory sync service image.
      run: |
        docker build --no-cache -t samply/directory_sync_service .

    - name: Build local image that will load data from files to FHIR store (Blaze).
      working-directory: ci/data_loader
      run: |
        docker build --no-cache -t samply/data_loader .

    - name: Run integration stack (docker compose)
      working-directory: ci
      run: |
        set -euo pipefail
        # Bring the stack up, fail fast if a container exits non-zero.
        docker compose up --abort-on-container-exit --quiet-pull

    - name: Show compose logs on failure
      if: failure()
      working-directory: ci
      run: |
        docker compose logs --no-color || true

    - name: Compare output of integration run with reference data
      working-directory: ci
      run: |
        set -euo pipefail
        bash compare_test_results_with_reference.sh crc_full

    - name: Tear down stack
      if: always()
      working-directory: ci
      run: |
        docker compose down -v || true
        rm -rf output/* || true
        docker volume rm -f store-db-data || true

      # END: integration testing

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker meta
      id: docker-meta
      uses: docker/metadata-action@v4
      with:
        images: |
          samply/directory_sync_service
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha,format=long

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ steps.docker-meta.outputs.tags }}
        labels: ${{ steps.docker-meta.outputs.labels }}

