# This workflow is triggered whenever a new git tag matching
# the pattern "v.*.*.*" is pushed to GitHub. It will automatically
# create a new GitHub release.

name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+**'

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-22.04
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
