package de.samply.directory_sync_service.service;

import de.samply.directory_sync_service.sync.Sync;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.quartz.JobDataMap;
import org.quartz.JobExecutionContext;
import org.quartz.JobExecutionException;
import org.quartz.StatefulJob;
import org.quartz.DisallowConcurrentExecution;

/**
 * Job for starting a synchronization with the Directory.
 * <p>
 * Can handle single-run or repeated run operations.
 * <p>
 * Will not allow multiple instances of this job to run at the same time.
 */
@DisallowConcurrentExecution
public class DirectorySyncJob implements StatefulJob  {
    private static Logger logger = LogManager.getLogger(DirectorySyncJob.class);

    /**
     * Method used by Quartz to start a job.
     *
     * @param jobExecutionContext Not used, null value allowed.
     */
    @Override
    public void execute(JobExecutionContext jobExecutionContext) {
        // Get parameters
        JobDataMap data = jobExecutionContext.getJobDetail().getJobDataMap();
        Configuration configuration = (Configuration) data.get("configuration");

        execute(configuration);
    }

    /**
     * Method to launch a single run of the job.
     *
     * @param configuration Spring Boot configuration to be used for parameters.
     * @throws JobExecutionException
     */
    public void execute(Configuration configuration) {
        String retryMax = configuration.getRetryMax();
        String retryInterval = configuration.getRetryInterval();
        String directoryUrl = configuration.getDirectoryUrl();
        String fhirStoreUrl = configuration.getFhirStoreUrl();
        String directoryUserName = configuration.getDirectoryUserName();
        String directoryUserPass = configuration.getDirectoryUserPass();
        String directoryDefaultCollectionId = configuration.getDirectoryDefaultCollectionId();
        boolean directoryAllowStarModel = Boolean.parseBoolean(configuration.getDirectoryAllowStarModel());
        int directoryMinDonors = Integer.parseInt(configuration.getDirectoryMinDonors());
        int directoryMaxFacts = Integer.parseInt(configuration.getDirectoryMaxFacts());
        boolean directoryMock = Boolean.parseBoolean(configuration.getDirectoryMock());
        boolean directoryOnlyLogin = Boolean.parseBoolean(configuration.getDirectoryOnlyLogin());

        Sync.syncWithDirectoryFailover(retryMax, retryInterval, fhirStoreUrl, directoryUrl, directoryUserName, directoryUserPass, directoryDefaultCollectionId, directoryAllowStarModel, directoryMinDonors, directoryMaxFacts, directoryMock, directoryOnlyLogin);
    }

    /**
     * Test to see if the preconditions for executing a job are available.
     *
     * @param configuration Spring Boot configuration for this service.
     * @return True, if the preconditions are satidfied, false otherwise.
     */
    public boolean isExecutable(Configuration configuration) {
        String directoryUserName = configuration.getDirectoryUserName();
        String directoryUserPass = configuration.getDirectoryUserPass();
        if (directoryUserName == null || directoryUserName.isEmpty() || directoryUserPass == null || directoryUserPass.isEmpty()) {
            logger.warn("Directory user name or pass code is empty, will *not* perform Directory sync");
            return false;
        }

        return true;
    }

    /**
     * Provide the type of the job being run. This is a string, that is essentially arbitrary,
     * but it should have some relevance to the task bein executed, because it appears in
     * some of the diagnostics generated by Quartz.
     *
     * @return Job type.
     */
    public String getJobType() {
        return "directorySync";
    }
}
